package com.example.personal_studio.feature.scanner.enhance

import android.graphics.Bitmap
import android.graphics.Matrix
import android.graphics.PointF
import androidx.lifecycle.ViewModel
import androidx.lifecycle.viewModelScope
import com.example.personal_studio.data.scanner.BitmapIo
import com.example.personal_studio.data.scanner.EnhancePipeline
import com.example.personal_studio.domain.model.ScanFilter
import dagger.assisted.Assisted
import dagger.assisted.AssistedFactory
import dagger.assisted.AssistedInject
import dagger.hilt.android.lifecycle.HiltViewModel
import kotlinx.coroutines.flow.MutableStateFlow
import kotlinx.coroutines.flow.asStateFlow
import kotlinx.coroutines.launch
import java.io.File

data class EnhanceReviewUiState(
    // GRAYSCALE is our CamScanner-style "enhanced+sharp" mode — the sensible
    // default for document scans (keeps gray levels so small fonts survive).
    val currentFilter: ScanFilter = ScanFilter.GRAYSCALE,
    val displayedBitmap: Bitmap? = null,
    val isLoading: Boolean = true,
    /** 0..3 quarter-turns applied clockwise when displaying. Lets the user
     *  correct any residual rotation when auto-detect picked up the document
     *  in an unexpected orientation. */
    val rotationQuarters: Int = 0,
    /** The high-res warped bitmap serving COLOR + GRAYSCALE. Filter switches
     *  that read this value (via [selectFilter]) preserve the sharpness of
     *  the 3000-long-side decode. BW has a separate low-res base (see
     *  [warpedLowRes]) because its 3× supersample pipeline would OOM if fed
     *  the same high-res source. */
    val warpedColor: Bitmap? = null,
)

@HiltViewModel(assistedFactory = EnhanceReviewViewModel.Factory::class)
class EnhanceReviewViewModel @AssistedInject constructor(
    @Assisted private val capturedFilePath: String,
    @Assisted private val cornersBitmapPx: List<PointF>,
    private val pipeline: EnhancePipeline,
) : ViewModel() {

    // Keyed by (filter, rotationQuarters). The unrotated entries (rot=0) are
    // generated by the enhance pipeline; rotated variants are cheap Matrix-
    // rotations of those.
    private val cache = mutableMapOf<Pair<ScanFilter, Int>, Bitmap>()
    private val _state = MutableStateFlow(EnhanceReviewUiState())
    val state = _state.asStateFlow()

    /** Downscaled copy of the high-res warp sized for BW's supersample
     *  pipeline. Lazy-populated on first BW selection so the extra memory
     *  only exists when the user actually asks for it. */
    private var warpedLowRes: Bitmap? = null

    init {
        viewModelScope.launch {
            val file = File(capturedFilePath)
            // Edge detection (upstream VM) runs at LOW_RES_LONG_SIDE, so the
            // `cornersBitmapPx` we received live in that coordinate space.
            // To warp at HIGH_RES we need to scale those corners by the
            // ratio of actual decoded widths — both decodes use integer
            // sample factors so the ratio isn't exactly HIGH/LOW.
            val rawLow = BitmapIo.decodeDownscaled(file, LOW_RES_LONG_SIDE)
            val rawHigh = BitmapIo.decodeDownscaled(file, HIGH_RES_LONG_SIDE)
            val scaleToHigh = rawHigh.width.toFloat() / rawLow.width.toFloat()
            rawLow.recycle()
            val cornersHigh = cornersBitmapPx.map {
                PointF(it.x * scaleToHigh, it.y * scaleToHigh)
            }

            // Warp at high res — this is the canonical base for COLOR and
            // GRAYSCALE. ~3000 px long side (≈225 DPI on A4), noticeably
            // sharper than the 2000 px path we were on before.
            val warped = pipeline.warpAndFilter(rawHigh, cornersHigh, ScanFilter.COLOR)
            rawHigh.recycle()
            cache[ScanFilter.COLOR to 0] = warped

            val initial = pipeline.applyFilter(warped, ScanFilter.GRAYSCALE)
            cache[ScanFilter.GRAYSCALE to 0] = initial
            _state.value = EnhanceReviewUiState(
                currentFilter = ScanFilter.GRAYSCALE,
                displayedBitmap = initial,
                isLoading = false,
                warpedColor = warped,
            )
        }
    }

    fun selectFilter(filter: ScanFilter) = viewModelScope.launch {
        val rot = _state.value.rotationQuarters
        val cached = cache[filter to rot]
        if (cached != null) {
            _state.value = _state.value.copy(
                currentFilter = filter,
                displayedBitmap = cached,
                isLoading = false,
            )
            return@launch
        }
        _state.value = _state.value.copy(currentFilter = filter, isLoading = true)
        val bmp = obtainDisplayBitmap(filter, rot) ?: return@launch
        _state.value = _state.value.copy(displayedBitmap = bmp, isLoading = false)
    }

    /** Rotate clockwise by 90°. Cycles 0 → 1 → 2 → 3 → 0 in quarter-turns. */
    fun rotateClockwise() = viewModelScope.launch {
        val newRot = (_state.value.rotationQuarters + 1) % 4
        _state.value = _state.value.copy(rotationQuarters = newRot, isLoading = true)
        val bmp = obtainDisplayBitmap(_state.value.currentFilter, newRot) ?: return@launch
        _state.value = _state.value.copy(displayedBitmap = bmp, isLoading = false)
    }

    /**
     * Fetch or build the bitmap for this filter + rotation. Rotation 0 is
     * built via the enhance pipeline; rotated variants are derived by
     * `Matrix.postRotate()` from the rot-0 bitmap, which is fast since no
     * resampling happens on 90° multiples.
     */
    private suspend fun obtainDisplayBitmap(filter: ScanFilter, rot: Int): Bitmap? {
        cache[filter to rot]?.let { return it }
        // Ensure the rot-0 (canonical) bitmap exists first.
        val rotZero = cache[filter to 0] ?: run {
            val base = baseFor(filter) ?: return null
            val out = pipeline.applyFilter(base, filter)
            cache[filter to 0] = out
            out
        }
        if (rot == 0) return rotZero
        val rotated = rotateQuarters(rotZero, rot)
        cache[filter to rot] = rotated
        return rotated
    }

    private fun rotateQuarters(src: Bitmap, quarters: Int): Bitmap {
        val m = Matrix().apply { postRotate(quarters * 90f) }
        return Bitmap.createBitmap(src, 0, 0, src.width, src.height, m, true)
    }

    private fun baseFor(filter: ScanFilter): Bitmap? {
        val warpedHigh = _state.value.warpedColor ?: return null
        return when (filter) {
            // BW's supersample pipeline allocates ~3 × float32 mats at 3× the
            // source size. Feeding it the high-res warp would OOM, so we keep
            // BW on the old 2000-long-side base via a lazily-scaled copy.
            ScanFilter.BW -> warpedLowRes ?: downscaleForBw(warpedHigh).also { warpedLowRes = it }
            else -> warpedHigh
        }
    }

    private fun downscaleForBw(warpedHigh: Bitmap): Bitmap {
        val longSide = maxOf(warpedHigh.width, warpedHigh.height)
        if (longSide <= LOW_RES_LONG_SIDE) return warpedHigh
        val ratio = LOW_RES_LONG_SIDE.toFloat() / longSide
        return Bitmap.createScaledBitmap(
            warpedHigh,
            (warpedHigh.width * ratio).toInt().coerceAtLeast(1),
            (warpedHigh.height * ratio).toInt().coerceAtLeast(1),
            true,
        )
    }

    @AssistedFactory
    interface Factory {
        fun create(capturedFilePath: String, cornersBitmapPx: List<PointF>): EnhanceReviewViewModel
    }

    companion object {
        /** EdgeDetectViewModel uses BitmapIo's default 2000 — must match. */
        private const val LOW_RES_LONG_SIDE = 2000

        /** Target long side for COLOR + GRAYSCALE warps. ~225 DPI on A4,
         *  noticeable sharpness gain over 2000 (~150 DPI) for text-dense
         *  documents without blowing through the Android app heap. */
        private const val HIGH_RES_LONG_SIDE = 3000
    }
}
